{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "harvester.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harvester.labels" . | nindent 4 }}
stringData:
  client.crt: |
{{ required "tls.clientCert is required" .Values.tls.clientCert | indent 4 }}
  client.key: |
{{ required "tls.clientKey is required" .Values.tls.clientKey | indent 4 }}
{{- if .Values.tls.caCert }}
  ca.crt: |
{{ .Values.tls.caCert | indent 4 }}
{{- end }}
{{- end }}
