{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "harvester.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harvester.labels" . | nindent 4 }}
stringData:
  {{- if .Values.tls.clientCert }}
  client.crt: {{ .Values.tls.clientCert | quote }}
  {{- end }}
  {{- if .Values.tls.clientKey }}
  client.key: {{ .Values.tls.clientKey | quote }}
  {{- end }}
  {{- if .Values.tls.caCert }}
  ca.crt: {{ .Values.tls.caCert | quote }}
  {{- end }}
{{- end }}
