name: Feature Pull Request

permissions:
  contents: read
  security-events: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true


on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'main'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml
    with:
      version_bump: 'patch'
      components: '["inspire_to_arc"]'
    secrets: inherit

  check:
    name: Check
    uses: ./.github/workflows/reusable-check.yml
    with:
      version: ${{ needs.build.outputs.version }}
      components: '["inspire_to_arc"]'
    secrets: inherit
