name: Feature Pull Request

permissions:
  contents: read
  security-events: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'main'

jobs:
  code-quality:
    name: Code Quality
    uses: fairagro/m4.2_middleware_devinfra/.github/workflows/reusable-code-quality.yml@main
    with:
      python_package_root: middleware
      components: '["harvester"]'
    secrets: inherit

  build:
    name: Build
    uses: fairagro/m4.2_middleware_devinfra/.github/workflows/reusable-build.yml@main
    with:
      components: '["harvester"]'
      image_base_name: fairagro-advanced-middleware
    secrets: inherit

  check:
    name: Check
    needs: build
    if: always() && needs.build.result == 'success'
    uses: fairagro/m4.2_middleware_devinfra/.github/workflows/reusable-check.yml@main
    with:
      version: ${{ needs.build.outputs.version }}
      components: '["harvester"]'
      image_base_name: fairagro-advanced-middleware
    secrets: inherit
