name: Helm Chart Pre Release

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  helm:
    uses: fairagro/m4.2_middleware_devinfra/.github/workflows/reusable-helm-pre-release.yml@main
    with:
      chart_dir: helm/harvester
      chart_name: fairagro-advanced-middleware-harvester-chart
      dockerhub_namespace: zalf
    secrets: inherit
